# Generated by Django 5.1.3 on 2025-01-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_usermodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_id',
            field=models.CharField(unique=True, verbose_name='user_id'),
        ),
    ]
