# Generated by Django 5.1.3 on 2025-01-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_usermodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animemodel',
            name='rejissor',
        ),
        migrations.AddField(
            model_name='animemodel',
            name='rejissyor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejissyor', to='anime.usermodel'),
        ),
    ]
