# Generated by Django 5.1.3 on 2025-01-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_remove_animemodel_rejissyor_animemodel_rejissor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animemodel',
            old_name='rejissor',
            new_name='rejissyor',
        ),
    ]
